### PR TITLE
Update parinfer.py to 3.12.0 and make a few optimizations

### PR DESCRIPTION
**Pull request by oconnor0**
* Direct update from reference implementation.
* Python-specific performance improvements.
* Update tests to use unittest instead of separate package.
* About 30% to 50% slower than 0.7.0.
* Requires Python 3.

I figured I would open this pull request rather than wait til I get the code "perfect" since that will likely never happen, but please suggest changes or requirements for accepting the pull request or whatever else.

### CODE REVIEW

**Comment by oakmac** [comment]
Just a head's up: I have seen this, but not have the time to properly review it. At first glance looks amazing :pray: Will make some time tomorrow to thoroughly review :smile: (same situation for the sublime text plugin PR)

**Comment by oakmac** [comment]
> About 30% to 50% slower than 0.7.0.

Any ideas why this might be case? This is not a blocker; I'm just curious.

**Comment by oakmac** [comment]
Strong work here - thank you for taking on this effort :muscle:

**Comment by oconnor0** [comment]
> 
> 
> > About 30% to 50% slower than 0.7.0.
> 
> Any ideas why this might be case? This is not a blocker; I'm just curious.

@oakmac Not entirely sure. I assumed it was because the complexity of the algorithm increased quite a bit.

**Pull request merged**
